name: Universal Remote
favicon: null
layout_spectrum: 0.43387544178403914
typography_spectrum: 0.13034574105404317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8343313373625278
  lightness: 0.566951539600268
  saturation: 0.9328654406126589
  rhythmicContrast: 0.3331169420853257
purpose: []
