name: Universal Remote
favicon: null
layout_spectrum: 0.23545
typography_spectrum: 0.28468
title: 'Universal Remote: The Live Quiz Show Experience'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-210195-19
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
